### ISSUE TITLE
typeid not demangled

### ISSUE THREAD

**Issue by madsboettgerhansen** [IanHG/cutee#10] opened 2019-05-24 08:04 UTC
Got this from a failed test, compiled with gcc.
```
   *** ParamsTimTdvcc<std::complex<Nb>,GeneralMidasVector>; DiffNorm2 ***
   error        Wrong diffnorm2.
   file         /home/madsbh/programs/midas_tdvcc2_ode/test/TdvccTest.h:633

   expected     8.5332062238e+00 [d]
   got          8.5332062238e+00 [d]
```

cutee-2.0.3

**Comment by IanHG** [comment] 2019-05-28 12:41
The feature works as intended.

This is not a cutee issue, but an issue with the client code. Closing.

**Closed by IanHG** 2019-05-28 12:41 UTC
